name: GitHub Actions Demo
on: [push]
jobs:
  Robot-Playwright-On-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}